require("packer-config")
require("options")
require("keymap-config")
require("autopairs-config")
require("lualine-config")
require("colors-config.nightfox")
require("nvim-tree-config")
require("treesitter-config")
require("cmp-config")
--> lsp modules
require("lsp-config")
